name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore /DummyBackend/DummyBackend.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore DummyBackend/DummyBackend.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal DummyBackend/DummyBackend.sln
    - name: Publish
      run: dotnet publish -c Release --no-restore -o /app DummyBackend/DummyBackend.sln
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: /app
