name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore DunmmyBackend/DunmmyBackend.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore DunmmyBackend/DunmmyBackend.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal DunmmyBackend/DunmmyBackend.sln
  
  publish:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Publish
      run: dotnet publish -c Release --no-restore -o app DunmmyBackend/DunmmyBackend.sln
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: app
  
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        app-name: publicthrashpandas
        package: app
